version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"  
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URI=${NEXT_PUBLIC_API_URI}
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "9090:9090"  
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
      - PROJECT_URL=${NEXT_PUBLIC_API_URI}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
